# Generated by Django 6.0.1 on 2026-01-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comments_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cooked_score',
            field=models.IntegerField(default=0),
        ),
    ]
