# Generated by Django 6.0.1 on 2026-01-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_cooked_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cooked_score',
        ),
    ]
