# Generated by Django 6.0.1 on 2026-01-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_cookedscore_options_post_voters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='voters',
        ),
    ]
