# Generated by Django 6.0.1 on 2026-01-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_claculated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_count',
        ),
        migrations.DeleteModel(
            name='CookedScore',
        ),
    ]
