# Generated by Django 6.0.1 on 2026-01-11 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_cooked_score_post_no_votes_post_total_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cooked_score',
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('post', 'user')},
        ),
    ]
