# Generated by Django 6.0.1 on 2026-01-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0001_initial'),
        ('posts', '0011_remove_post_cooked_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_pannel.topic'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
