# Generated by Django 6.0.1 on 2026-01-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='post',
            new_name='post_id',
        ),
    ]
